version: "2.4"
services:
  app:
    build: .
    image: pam_oidc:v0.0.2
    # environment:
    #   - RUSTFLAGS=-C link-arg=-undefined
    #   - RUSTFLAGS=-C target-feature=-crt-static
    #   - DISPLAY
    # command: ./target/release/pam_oidc
    command: tail -f /dev/null
    # user: "1000:0"
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    # - seccomp:unconfined
    # ports:
    #   - 2345:2345
    volumes:
      - ./sample.yaml:/workspace/sample.yaml
networks:
  default:
    external:
      name: node-oidc-provider_default