# docker compose up --build
# docker buildx bake --set "*.platform=linux/amd64" --load
version: "2.4"
services:
  app:
    build: .
    image: pam_oidc:v0.0.3
    # environment:
      # - RUSTFLAGS=-C link-arg=-undefined
      # - RUSTFLAGS=-C target-feature=-crt-static
    command: tail -f /dev/null
    volumes:
      - ./config/service_example:/etc/pam.d/oidc # add a 'oidc' config that utilizes pam_oidc
      - ./config/libpam_oidc.yaml:/etc/datajoint/libpam_oidc.yaml # add pam_oidc-specific config
      - ./tests/test.py:/workspace/test.py # python test
      - ./pam-oidc:/workspace/pam-oidc # mount source for dev
